### ISSUE TITLE
Feature request: Non-fatal error for reading corrupted fasta records (skbio.io.read)

### ISSUE THREAD

**Issue by jolespin** [scikit-bio/scikit-bio#1470]
I encountered an error (below) reading in corrupted UNITE fasta files (fungal ITS sequence database).  Most of the sequences were fine but a few of them had characters outside of the DNA alphabet, when a record contained a bad character, the parser threw a fatal error.

It could be useful to have an error message giving the header of the corrupted entry and then continue reading the file (i.e. a non-fatal error).  

The sequences I was using were from: https://unite.ut.ee/sh_files/UNITE_public_22.08.2016.fasta.zip
I gave them a list of which ones were corrupted and I think they fixed it in the newer release. 
When I first encountered this error, it took me a bit to figure out which entries were corrupted. 

```
path = "/Users/Mu/Downloads/UNITE_public_22.08.2016.fasta"
>>> for seq_record in skbio.io.read(path, constructor=skbio.DNA, format="fasta", lowercase=True):
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/io/registry.py", line 506, in <genexpr>
    return (x for x in itertools.chain([next(gen)], gen))
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/io/registry.py", line 531, in _read_gen
    yield from reader(file, **kwargs)
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/io/registry.py", line 1008, in wrapped_reader
    yield from reader_function(fhs[-1], **kwargs)
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/io/format/fasta.py", line 677, in _fasta_to_generator
    **kwargs)
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py", line 336, in __init__
    self._validate()
  File "/Users/Mu/anaconda/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py", line 360, in _validate
    list(self.alphabet)))
ValueError: Invalid character in sequence: b'U'.
Valid characters: ['R', 'H', 'V', 'B', 'N', 'W', 'S', 'C', 'M', '.', 'T', 'K', '-', 'D', 'G', 'Y', 'A']
Note: Use `lowercase` if your sequence contains lowercase characters not in the sequence's alphabet.
```

One of the entries was: 

> >UDB002609|k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Thelephorales;f__Thelephoraceae;g__unidentified;s__Thelephoraceae_sp|SH189369.07FU
> CCGAATTGTTGACACGAGTTGTTGCTGGCCTTCAAACGGGGGCACGTGCACGCTCTGTTTATACATCCACCCACCCCTGTGCACCTTTTGTAGCTCTGTGGTCTGGAGGCTCCGCTTCCCTTCCGCGGTTCTACGTCTTTACACACACACGTTAAAGAAGTCTGTGGAATGTACGCCGCGTTTACGCAATACAATACAACTTTCAGCAACGGATCTCTTGGCTCTCGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACCTTGCGCCCTTTGGCTATTCCGAAGGGCATGCCTGTTTGAGTATCATGAACACCTCAACCCTCACGGTTCCTCGTGATGGGCTTGGACTTGGGGGCTTTGTTGGCCTGTGGTCAGCTCTCCTCAAATAAATCAGCTCGCCAGTGTCTGGCGGCATCATGGGTGTGATAACCATCTACGCTTGTGATCGCCTGCGAGGTAAACCTCTGGTCTGCAGAGGTTCGCTGGAGCTTATAGATGTCTCTCCTCCGTGAAGACAGCTGTCTGAAGTTCGATCTCAAATCAGGTAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAGGAAAAGAAACTAACAAGGATTCCCCTAGTAACTGCGAGTGAAGCGGGAAGAGCTCAAATTTAAAATCTGGCGTGCCTCCGGTCGTCCGAGTTGTAGTCTGGAGAAGCGTTTTCCGTGTTGGACCGTGTATAAGTCTCTTGGAACAGGGCGTCATAGAGGGTGAGAATCCCGTCTTTGACACGGACTGCCAATGCTTTGTGATGCGCTCTCAAAGAGTCGAGTTGTTTGGGAATGCAGCTCAAAATGGGTGGTAAATTCCATCTAAAG**UDB**
> 

Note: this is migrated from https://github.com/biocore/scikit-bio/issues/1438

**Comment by ebolyen** [comment]
:+1: I think this could be handled like [`open`'s `errors` parameter](https://docs.python.org/3.6/library/functions.html#open). I think it should stay a fatal error by default, but if you have a handler you can opt out because you've given skbio something to do instead of except.

**Comment by jolespin** [comment]
What if it still threw a fatal error but also gave the header in which the error occurred for debugging purposes?
