### ISSUE TITLE
Skbio development environmental installation issues

### ISSUE THREAD

**Issue by constellation99** [scikit-bio/scikit-bio#1883]
## Summary

While attempting to install `scikit-bio` for development, I received the following error message. This error occurred with both the editable and non-editable installations. I was following the steps for setting up a development environment for scikit-bio listed [here](https://github.com/scikit-bio/scikit-bio/blob/master/.github/CONTRIBUTING.md), and the issue occured on step 5. 

## Error Message

     (skbio-dev) ajcagle@~/scikit-bio$ pip install --no-deps -e .

      #...snip... trimming error message

      gcc -pthread -B /home/ajcagle/miniconda3/envs/skbio-dev/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/ajcagle/miniconda3/envs/skbio-dev/include -fPIC -O2 -isystem /home/ajcagle/miniconda3/envs/skbio-dev/include -fPIC -Iskbio/alignment -I/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/numpy/core/include -I/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/numpy/core/include -I/home/ajcagle/miniconda3/envs/skbio-dev/include/python3.11 -I/home/ajcagle/miniconda3/envs/skbio-dev/include/python3.11 -c skbio/alignment/_lib/ssw.c -o /tmp/tmpdw2bfp6_.build-temp/skbio/alignment/_lib/ssw.o -I. -fopenmp-simd -DSIMDE_ENABLE_OPENMP
      gcc: error: unrecognized command line option ‘-fopenmp-simd’
      Traceback (most recent call last):
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      /tmp/pip-build-env-k3za7s3e/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `scikit-bio` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building editable for scikit-bio
    Failed to build scikit-bio
    ERROR: Could not build wheels for scikit-bio, which is required to install pyproject.toml-based projects

## Environment

    (skbio-dev) ajcagle@~/scikit-bio$ uname -a
    Linux barnacle2 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

    (skbio-dev) ajcagle@~/scikit-bio$ python --version
    Python 3.11.6

    (skbio-dev) ajcagle@~/scikit-bio$ gcc --version
    gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    (skbio-dev) ajcagle@~/scikit-bio$ pip --version
    pip 23.3.1 from /home/ajcagle/miniconda3/envs/skbio-dev/lib/python3.11/site-packages/pip (python 3.11)

**Comment by qiyunzhu** [comment]
@constellation99 Thanks for reporting! I see the `-fopenmp-simd` issue, which could be related to certain low-level instructions needed for sequence alignment, which we plan to get rid of in a near future version. By the way, the GCC version (4.8.5) looks bit old. Would it be possible to try scikit-bio on a machine with newer GCC?

**Comment by constellation99** [comment]
@qiyunzhu Thanks for your help! I updated GCC and that seemed to fix the issue. I was able to install skbio successfully.

**Comment by wasade** [comment]
Thanks, @constellation99! What version were you successful with? It may not represent the lowest supported version but it provides a starting point

**Comment by constellation99** [comment]
Hi, @wasade! I updated GCC to the newest version, which is 13.2.0.
