### ISSUE TITLE
Compression differences on Windows

### ISSUE THREAD

**Issue by mataton** [scikit-bio/scikit-bio#2013]
In `skbio/io/tests/test_util.py` there are 6 tests which fail when running on Windows. All of them have to do with the contents of a compressed file not matching between Windows and other operating systems.

````
======================================================================
FAIL: test_open_bz2 (__main__.TestWriteTemporaryFile.test_open_bz2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 362, in test_open_bz2
    self.assertEqual(self.get_contents(self.bz2_file),
AssertionError: b'BZh91AY&SY\x92V\x8ax\x00\x00\x08W\x80\x00\x12@\x00\x0[154 chars]\xe0' != b'BZh91AY&SY\xfd\xaf\xddl\x00\x00\x06W\x80\x00\x10@\x00[167 chars]xeb`'

======================================================================
FAIL: test_open_bz2_encoding (__main__.TestWriteTemporaryFile.test_open_bz2_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 390, in test_open_bz2_encoding
    self.assertEqual(self.get_contents(self.bz2_encoded_file),
AssertionError: b'BZh91AY&SY<\xa7_S\x00\x00\x03E\x10\x00\x12 \x00\x00[70 chars]\xc0' != b'BZh91AY&SY\xb2\xe2*\xbc\x00\x00\x02E\x10\x00\x10 \x[71 chars]\x80'

======================================================================
FAIL: test_open_gzip (__main__.TestWriteTemporaryFile.test_open_gzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 355, in test_open_gzip
    self.compare_gzip_file_contents(self.get_contents(self.gzip_file),
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 341, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'\xb5\xb7\xf209\x00\x00\x00' != b'\x8a\x9d\xf4\x165\x00\x00\x00'

======================================================================
FAIL: test_open_gzip_encoding (__main__.TestWriteTemporaryFile.test_open_gzip_encoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 381, in test_open_gzip_encoding
    self.compare_gzip_file_contents(
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\tests\test_util.py", line 341, in compare_gzip_file_contents
    self.assertEqual(a[-8:], b[-8:])
AssertionError: b'Q\x05Y\xa2\x07\x00\x00\x00' != b'&\x05\xd3\xe1\x05\x00\x00\x00'

----------------------------------------------------------------------
````

**Comment by qiyunzhu** [comment]
This has been addressed I think. Closing.
