### ISSUE TITLE
Support for stdin for at least FASTA/FASTQ

### ISSUE THREAD

**Issue by wasade** [scikit-bio/scikit-bio#2017]
Many libraries support streaming FASTA/FASTQ data through stdin. It would be pleasant for that mode of operation to be supported as it is handy when writing small stream processors

```bash
$ cat test.py
import skbio
import sys
for r in skbio.read(sys.stdin, format='fasta'):
    print(r.metadata['id'])
$ cat q.fna 
>qx1
TTTTTTTTT
>qx2
TTTTTTTTNNNNNN
$ cat q.fna | python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    for r in skbio.read(sys.stdin, format='fasta'):
  File "/home/mcdonadt/miniconda3/envs/test/lib/python3.8/site-packages/skbio/io/registry.py", line 1160, in read
    return io_registry.read(file, format=format, into=into, verify=verify,
  File "/home/mcdonadt/miniconda3/envs/test/lib/python3.8/site-packages/skbio/io/registry.py", line 506, in read
    return (x for x in itertools.chain([next(gen)], gen))
  File "/home/mcdonadt/miniconda3/envs/test/lib/python3.8/site-packages/skbio/io/registry.py", line 529, in _read_gen
    reader, kwargs = self._init_reader(file, fmt, into, verify, kwargs,
  File "/home/mcdonadt/miniconda3/envs/test/lib/python3.8/site-packages/skbio/io/registry.py", line 543, in _init_reader
    backup = file.tell()
io.UnsupportedOperation: underlying stream is not seekable
```

**Comment by RaeedA** [comment]
Hey! This issue seems to stem from the fact that stdin isn't a seekable stream, which messes with the file sniffers. The problem specifically arises when [saving the pointer position](https://github.com/scikit-bio/scikit-bio/blob/e3a27f56970fded68ba7561767cec41e47ba3c78/skbio/io/registry.py#L532) before sniffing, and [restoring it afterwards](https://github.com/scikit-bio/scikit-bio/blob/e3a27f56970fded68ba7561767cec41e47ba3c78/skbio/io/registry.py#L534C1-L534C17).

I found that commenting them out caused the piping to work as expected, but with residual warnings.
```bash
(skbio-dev) azomss-air:scikit-bio raeedazom$ cat skbio/io/q.fna | python skbio/io/temp.py 
/Users/raeedazom/Documents/Coding/scikit-bio/skbio/io/registry.py:922: FormatIdentificationWarning: '_fasta_sniffer' has encountered a problem.
Please send the following to our issue tracker at
https://github.com/scikit-bio/scikit-bio/issues

Traceback (most recent call last):
  File "/Users/raeedazom/Documents/Coding/scikit-bio/skbio/io/registry.py", line 917, in wrapped_sniffer
    fh.seek(0)
io.UnsupportedOperation: underlying stream is not seekable

  warn(
/Users/raeedazom/Documents/Coding/scikit-bio/skbio/io/registry.py:536: FormatIdentificationWarning: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> does not look like a fasta file
  warn(
qx1
qx2
```
To fix this, I plan on adding a seekable vs nonseekable option which can bypass seeking and telling for nonseekable I/O.

**Comment by mataton** [comment]
It's not a long term solution, but the desired functionality is possible currently if you do the following in `test.py`:

```python
import skbio
import sys
for r in skbio.read(sys.stdin, format='fasta', verify=False):
    print(r.metadata['id'])
```

The only cost of `verify=False` is that the function does not invoke skbio's sniffers, so the user needs to be more confident in their file formats. A solution including functional sniffers with support for `stdin` is desired, just wanted this workaround to be documented.
