### ISSUE TITLE
Issues with `SampleMetadata` read/write in Windows

### ISSUE THREAD

**Issue by mataton** [scikit-bio/scikit-bio#2048]
On windows, one of the last remaining unit tests which fails is `test_simple` from `skbio/io/format/tests/test_sample_metadata.py`. Here is the output of the failed test.

````
ERROR: test_simple (__main__.TestRoundtrip.test_simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\format\tests\test_sample_metadata.py", line 77, in test_simple
    md2 = SampleMetadata.read(self.filepath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\registry.py", line 648, in read
    return registry.read(file, into=cls, format=format, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\registry.py", line 500, in read
    return self._read_ret(file, format, into, verify, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\registry.py", line 508, in _read_ret
    return reader(file, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\registry.py", line 1007, in wrapped_reader
    return reader_function(fhs[-1], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\io\format\sample_metadata.py", line 358, in _sample_metadata_read
    return MetadataReader(fh).read(SampleMetadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\metadata\io.py", line 101, in read
    ids, data = self._read_data(header)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maton\qlab\skbio\windows\github\scikit-bio\skbio\metadata\io.py", line 316, in _read_data
    raise MetadataFileError(
skbio.metadata.io.MetadataFileError: Found directive '#sk:types' outside of the directives section of the file. Directives may only appear immediately after the header.

There may be more errors present in the metadata file. To get a full report, sample/feature metadata files can be validated with Keemei: https://keemei.qiime2.org

Find details on QIIME 2 metadata requirements here: https://docs.qiime2.org/

----------------------------------------------------------------------
````

I've recreated the test in a notebook on windows, and have noticed that the `write` function from the `SampleMetadata` class inserts `#sk:types` even when there weren't any in the original file, and it seems to insert at the wrong position. See below.

````python
import tempfile
import os
import pandas as pd
from skbio.metadata._metadata import SampleMetadata

temp_dir_obj = tempfile.TemporaryDirectory(prefix='sample-metadata-temp')
temp_dir = temp_dir_obj.name
filepath = os.path.join(temp_dir, 'metadata.tsv')

# This file is found in skbio/io/format/tests/data. I copied it into the current directory for this notebook
fp = 'sample-metadata-comments-mixed-case.tsv'

md1 = SampleMetadata.read(fp)
md1.to_dataframe()
````
![Screenshot 2024-06-12 150245](https://github.com/scikit-bio/scikit-bio/assets/62309966/0753e42e-c6fe-4a62-84c5-9de210342718)

````python
md1.write(filepath)
test = pd.read_csv(filepath, sep='\t')
test
````
![Screenshot 2024-06-12 150437](https://github.com/scikit-bio/scikit-bio/assets/62309966/d3162ac7-c809-462e-b118-1b5dd0629e9d)

So, when the test tries to read from `filepath` into a new metadata object `md2` it fails with `skbio.metadata.io.MetadataFileError: Found directive '#sk:types' outside of the directives section of the file. Directives may only appear immediately after the header.`

**Comment by LarsHunger** [comment]
I see, I will look at it when I have a minute.
