### ISSUE TITLE
Error : installing scikit-bio with poetry

### ISSUE THREAD

**Issue by iBuitron** [scikit-bio/scikit-bio#2101]
Hi there!

i'm installing scikit-bio with poetry:

`poetry add scikit-bio`
no error on installing.

but when i trying to run anywhere, as example:

```
import skbio

print(skbio.__version__)
```

i'm getting this error:

```
Traceback (most recent call last):
  File "/home/reveur/python/environmental/quickBio/ed.py", line 1, in <module>
    import skbio
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/__init__.py", line 12, in <module>
    import skbio.io  # noqa
    ^^^^^^^^^^^^^^^
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/io/__init__.py", line 290, in <module>
    import_module("skbio.io.format.clustal")
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/io/format/clustal.py", line 148, in <module>
    from skbio.alignment import TabularMSA
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/alignment/__init__.py", line 211, in <module>
    from ._tabular_msa import TabularMSA
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/alignment/_tabular_msa.py", line 18, in <module>
    from skbio.sequence import Sequence
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/sequence/__init__.py", line 329, in <module>
    from ._substitution import SubstitutionMatrix
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/sequence/_substitution.py", line 12, in <module>
    from skbio.stats.distance import DissimilarityMatrix
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/stats/__init__.py", line 69, in <module>
    from ._subsample import subsample_counts, isubsample
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/skbio/stats/_subsample.py", line 18, in <module>
    from biom import subsample as biom_subsample
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/biom/table.py", line 196, in <module>
    from ._filter import _filter
  File "biom/_filter.pyx", line 1, in init biom._filter
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Another error with biom (it coming with scikit-bio) 

```
import biom

print(biom.__version__)

Traceback (most recent call last):
  File "/home/reveur/python/environmental/quickBio/ed.py", line 1, in <module>
    import biom
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/reveur/python/environmental/quickBio/.venv/lib/python3.11/site-packages/biom/table.py", line 196, in <module>
    from ._filter import _filter
  File "biom/_filter.pyx", line 1, in init biom._filter
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

if i installing with pip, not error.
but all my dependencies is manage with poetry, any way to fix that? 

```
import numpy
print(numpy.__version__) # 2.0.1

no error here
```

**Comment by qiyunzhu** [comment]
Hi @iBuitron It looks like the most plausible reason is that the skbio copy you were installing attempted to build against NumPy 1.x. Is there a command-line way to check what version of skbio was being installed by poetry? If below 0.6.1, then it won't work with NumPy 2.0. If 0.6.1 or above, it should, but there may be a chance that the build process is isolated and not respecting the NumPy version (2.0) you already installed in the system. This is something you can check. I am not familiar with poetry though...

**Comment by mataton** [comment]
@zorbax Great! I agree, closing now.
