### ISSUE TITLE
Striped Smith Waterman Alignment Pickle Support

### ISSUE THREAD

**Issue by Spill-Tea** [scikit-bio/scikit-bio#2160]
The StripedSmithWaterman class cannot be multiprocessed, because the class cannot be pickled. A `__reduce__` method is needed to support pickling, and thus multiprocessing of the class. The `__cinit__` of the class may also need to be updated, to make it easier to preserve initial user input args.

## System Info
python version: 3.12.3
skbio version: 0.6.2
OS: Sonoma 14.4

## Minimal Example
```python
from multiprocessing import Pool
from skbio.alignment import StripedSmithWaterman as ssw

instance = ssw("ATGC")
sequences: list[str] = ["ATGC", "TTGC"]
with Pool() as p:
    data = list(p.imap_unordered(instance, sequences))

```

## Traceback
```bash
Traceback (most recent call last):
  File "lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
  File "lib/python3.12/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "lib/python3.12/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "<stringsource>", line 2, in skbio.alignment._ssw_wrapper.StripedSmithWaterman.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by Spill-Tea** [comment]
@qiyunzhu The prototype looks exciting. Perhaps instead, we could include multiprocess / pickle support as part of the requirements for the new alignment interface.

In the interim, if others face a similar or a related issue, here is a minimal workaround. We can build a pickleable python interface by subclassing the current StripedSmithWaterman class:

```python

from skbio.alignment import StripedSmithWaterman as ssw

class SmithWaterman(ssw):
    def __new__(cls, *args, **kwargs):
        obj = super().__new__(cls, *args, **kwargs)
        obj.__reduce_args__ = args, kwargs

        return obj

    def __setstate__(self, state):
        self.__dict__.update(state)

    def __reduce__(self):
        return SmithWaterman, *self.__reduce_args__

```

**Comment by qiyunzhu** [comment]
@Spill-Tea Thanks for the suggestion. It seems to be a quick patch that we can adopt. @mataton once you have a convenience would you like to try it?

**Comment by Spill-Tea** [comment]
The design I provided above does not correctly account for keyword arguments. Apparently, On load ([unpickling](https://github.com/python/cpython/blob/main/Lib/pickle.py#L1625C1-L1637C25)), the `__new__` method is called first. I could not find a way to call this with kwargs from a cython class implementing `__cinit__`. Providing a separate function did not work initially, like so:

```python
from typing import TypeVar
from skbio.alignment import StripedSmithWaterman as ssw

T = TypeVar("T")

def reconstruct(cls: type[T], *args, **kwargs) -> T:
    return cls(*args, **kwargs)

# showing only relevant change
class SmithWaterman(ssw):
    def __reduce__(self):
        args, kwargs = self.__reduce_args__
        return reconstruct, (SmithWaterman, *args), kwargs

```
Even On save (pickling), the kwargs are ignored. However, if we rename the reconstruct function to be called [`__newobj_ex__`](https://github.com/python/cpython/blob/main/Lib/pickle.py#L652C9-L671C33), it is used internally by pickle to support kwargs like so:

```python
from typing import TypeVar
from skbio.alignment import StripedSmithWaterman as ssw

T = TypeVar("T")

def __newobj_ex__(cls: type[T], *args, **kwargs) -> T:
    return cls.__new__(cls, *args, **kwargs)

class SmithWaterman(ssw):
    def __new__(cls, *args, **kwargs):
        obj = super().__new__(cls, *args, **kwargs)
        obj.__reduce_args__ = args, kwargs

        return obj

    def __setstate__(self, state): ...

    def __reduce__(self):
        return __newobj_ex__, (SmithWaterman, *self.__reduce_args__)

```

We can test this by:
```python
import pickle

instance = SmithWaterman("ATGC", gap_open_penalty=1)
new = pickle.loads(pickle.dumps(instance))

# NOTE: Here for brevity, but Equality (`__eq__`) dunder method not implemented on AlignmentResult class
new("AGC") == instance("AGC")
```

Since the default `gap_open_penalty` is much larger, if the keyword argument is not passed, it will only match `GC`.

**Comment by mataton** [comment]
Closing due to the removal of `ssw` from scikit-bio.
